kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
  name: img-switch
  region: ap-southeast-2
  version: "1.27"

managedNodeGroups:
  - name: primary
    instanceType: t3.small
    minSize: 1
    desiredCapacity: 1
    maxSize: 3
    spot: true
