# Stage 1: setup base image, install node_modules
FROM node:18-alpine as builder

# Setup root level node_modules for apps
WORKDIR /usr/src/app
COPY . .

RUN npm install -g pnpm \
    && pnpm install --prod \
    && pnpm run build


# Stage 2: Build production image
FROM node:18-alpine

# TODO: don't hardcode this in the dockerfile
ENV NODE_ENV=production

COPY --from=builder --chown=node:node /usr/src/app/package.json package.json
COPY --from=builder --chown=node:node /usr/src/app/next.config.js next.config.js
COPY --from=builder --chown=node:node /usr/src/app/node_modules node_modules
COPY --from=builder --chown=node:node /usr/src/app/.next .next
COPY --from=builder --chown=node:node /usr/src/app/public public

ARG USER="node"
USER $USER

ARG DEBUG_PORT=""
EXPOSE 3000 ${DEBUG_PORT}

CMD ["sh", "-c", "npm run start"]