name: ci

on:
  push:
    branches:
      - master

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.1"
      - name: Change to project directory
        run: cd ./api/image-wizard-api && ls
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v -cover ./...



  build-and-push-image:
    runs-on: ubuntu-latest
    needs: run-api-tests
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: ./api/image-wizard-api
            dockerfile: ./api/image-wizard-api/dockerfile
            image: jordanfox/image-wizard-api

          - context: ./frontend/image-wizard-frontend
            dockerfile: ./frontend/image-wizard-frontend/dockerfile
            image: jordanfox/image-wizard-frontend
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
