name: ci

on:
  push: 
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            jordanfox/image-wizard-api
            jordanfox/image-wizard-frontend
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest
            type=raw,value=latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image-wizard-api
        uses: docker/build-push-action@v5
        with:
          context: ./api/image-wizard-api
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Build and push image-wizard-frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/image-wizard-frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
